### ISSUE TITLE
HTTPS redirection

### ISSUE THREAD

**Issue by johnakash** [MorbZ/docker-web-redirect#1]
Is there anyway to redirect all HTTPS call to another domain / URL with HTTPS?

**Comment by MorbZ** [comment]
Sure, you can use something like [docker-letsencrypt-nginx-proxy-companion](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion) to use HTTPS on the referring container.

**Comment by johnakash** [comment]
No prob, I have updated the code and got that done.

**Comment by acarjuzaa** [comment]
Hi @johnakash what did you update to do this?

Thanks!
