### ISSUE TITLE
Image update

### ISSUE THREAD

**Issue by witten** [MorbZ/docker-web-redirect#2]
I know this project is pretty simple and thus doesn't need to receive a ton of updates itself. But it'd be great to get a Docker image rebuild and perhaps an updated nginx based image. Mostly for security and bug fix reasons. Thanks!

**Comment by timobrembeck** [comment]
@MorbZ especially since this repo has been updated, it would make even more sense to update the image on docker hub as well. Thanks in advance! :pray:

**Comment by MorbZ** [comment]
@timobrembeck It seems Docker Hub disabled automatic build pipelines if you are not paying their premium service, which I certainly won't do for an open source project.

**Comment by timobrembeck** [comment]
@MorbZ what about using GitHub actions for this?
https://docs.github.com/en/actions/publishing-packages/publishing-docker-images
